# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  save_hello_world_output:
    docker:
      - image: cimg/base:stable
    steps:
      -run: mkdir -p workspace
      -run:
        name: 'saving output'
        command: echo "Adding text to workspace folder" > workspace/echo-output
      -persist_to_workspace:
        root: workspace
        paths:
          - echo-output
  print_output_file:
    docker:
      - image: cimg/base:stable
    steps:
      - attach_workspace:
          at: /workspace
      - run: |
          if [[ `cat /workspace/echo-output` == "Adding text to workspace folder" ]]; then
            echo "It worked!";
          else
            echo "Nope!"; exit 1
          fi

workflows:
  save_hello_world_output_workflow:
    jobs:
      - say-hello
      - print_env_var
